name: flutter_training
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  riverpod: ^2.3.6
  json_annotation: ^4.8.1
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training.git
      ref: main
      path: packages/yumemi_weather
  flutter_riverpod: ^2.3.6


dev_dependencies:
  blendthink_lints: ^3.0.0
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/